-- Seed: Kontenrahmen (SKR03/SKR04) aus Excel 00_Kontenrahmen. Referenzdaten.
INSERT INTO kontenrahmen (skr03, skr04, bezeichnung, bwa_gruppe, guv_bilanz_position, kontenklasse, vorzeichen, aktiv) VALUES
  ('8000', '4000', 'Umsatzerlöse 19% USt', 'Umsatz', 'GuV: Umsatzerlöse', 'Erlöse', '+', TRUE),
  ('8100', '4100', 'Umsatzerlöse 7% USt', 'Umsatz', 'GuV: Umsatzerlöse', 'Erlöse', '+', TRUE),
  ('8200', '4200', 'Steuerfreie Umsätze §4 UStG', 'Umsatz', 'GuV: Umsatzerlöse', 'Erlöse', '+', TRUE),
  ('8300', '4300', 'Umsatzerlöse Ausland (EU)', 'Umsatz', 'GuV: Umsatzerlöse', 'Erlöse', '+', TRUE),
  ('8400', '4400', 'Umsatzerlöse Drittland', 'Umsatz', 'GuV: Umsatzerlöse', 'Erlöse', '+', TRUE),
  ('8500', '4500', 'Provisionserlöse', 'Umsatz', 'GuV: Umsatzerlöse', 'Erlöse', '+', TRUE),
  ('8600', '4600', 'Mieterlöse', 'Umsatz', 'GuV: Umsatzerlöse', 'Erlöse', '+', TRUE),
  ('8700', '4700', 'Erlöse aus Anlagenverkäufen', 'Sonstige Erlöse', 'GuV: Sonstige betriebliche Erlöse', 'Erlöse', '+', TRUE),
  ('8900', '4900', 'Andere sonstige Erlöse', 'Sonstige Erlöse', 'GuV: Sonstige betriebliche Erlöse', 'Erlöse', '+', TRUE),
  ('8910', '4910', 'Bestandsveränderungen', 'Bestandsveränd.', 'GuV: Bestandsveränderungen', 'Erlöse', '+', TRUE),
  ('3000', '5000', 'Wareneinkauf 19% VSt', 'Wareneinsatz', 'GuV: Materialaufwand', 'Aufwand', '-', TRUE),
  ('3100', '5100', 'Wareneinkauf 7% VSt', 'Wareneinsatz', 'GuV: Materialaufwand', 'Aufwand', '-', TRUE),
  ('3200', '5200', 'Wareneinkauf steuerfreie Einnahmen', 'Wareneinsatz', 'GuV: Materialaufwand', 'Aufwand', '-', TRUE),
  ('3400', '5400', 'Bezogene Leistungen', 'Fremdleistungen', 'GuV: Materialaufwand', 'Aufwand', '-', TRUE),
  ('3500', '5500', 'Hilfsstoffe & Betriebsmittel', 'Wareneinsatz', 'GuV: Materialaufwand', 'Aufwand', '-', TRUE),
  ('3600', '5600', 'Roh- und Betriebsstoffe', 'Wareneinsatz', 'GuV: Materialaufwand', 'Aufwand', '-', TRUE),
  ('3800', '5800', 'Wareneingang ohne Vorsteuer', 'Wareneinsatz', 'GuV: Materialaufwand', 'Aufwand', '-', TRUE),
  ('4100', '6000', 'Löhne und Gehälter', 'Personal', 'GuV: Personalaufwand', 'Aufwand', '-', TRUE),
  ('4110', '6010', 'Gehälter Angestellte', 'Personal', 'GuV: Personalaufwand', 'Aufwand', '-', TRUE),
  ('4120', '6020', 'Löhne Arbeiter', 'Personal', 'GuV: Personalaufwand', 'Aufwand', '-', TRUE),
  ('4130', '6030', 'Gehälter Geschäftsführung', 'Personal', 'GuV: Personalaufwand', 'Aufwand', '-', TRUE),
  ('4140', '6040', 'Aushilfslöhne', 'Personal', 'GuV: Personalaufwand', 'Aufwand', '-', TRUE),
  ('4150', '6050', 'Sozialabgaben AG-Anteil', 'Personal', 'GuV: Personalaufwand', 'Aufwand', '-', TRUE),
  ('4160', '6060', 'Berufsgenossenschaft', 'Personal', 'GuV: Personalaufwand', 'Aufwand', '-', TRUE),
  ('4170', '6070', 'Betriebliche Altersvorsorge', 'Personal', 'GuV: Personalaufwand', 'Aufwand', '-', TRUE),
  ('4200', '6200', 'Personalnebenkosten', 'Personal', 'GuV: Personalaufwand', 'Aufwand', '-', TRUE),
  ('4210', '6300', 'Miete & Pacht', 'Raumkosten', 'GuV: Sonstige betriebliche Aufwände', 'Aufwand', '-', TRUE),
  ('4220', '6310', 'Strom und Heizung', 'Raumkosten', 'GuV: Sonstige betriebliche Aufwände', 'Aufwand', '-', TRUE),
  ('4230', '6320', 'Reinigung und Pflege', 'Raumkosten', 'GuV: Sonstige betriebliche Aufwände', 'Aufwand', '-', TRUE),
  ('4240', '6400', 'Kfz-Steuer & Versicherung', 'Kfz-Kosten', 'GuV: Sonstige betriebliche Aufwände', 'Aufwand', '-', TRUE),
  ('4250', '6410', 'Kfz-Reparaturen', 'Kfz-Kosten', 'GuV: Sonstige betriebliche Aufwände', 'Aufwand', '-', TRUE),
  ('4260', '6420', 'Kraftstoffe', 'Kfz-Kosten', 'GuV: Sonstige betriebliche Aufwände', 'Aufwand', '-', TRUE),
  ('4600', '6600', 'Werbekosten', 'Marketing', 'GuV: Sonstige betriebliche Aufwände', 'Aufwand', '-', TRUE),
  ('4610', '6610', 'Messen und Ausstellungen', 'Marketing', 'GuV: Sonstige betriebliche Aufwände', 'Aufwand', '-', TRUE),
  ('4650', '6650', 'Reisekosten Mitarbeiter', 'Reisekosten', 'GuV: Sonstige betriebliche Aufwände', 'Aufwand', '-', TRUE),
  ('4660', '6660', 'Reisekosten Unternehmer', 'Reisekosten', 'GuV: Sonstige betriebliche Aufwände', 'Aufwand', '-', TRUE),
  ('4670', '6670', 'Bewirtungskosten', 'Reisekosten', 'GuV: Sonstige betriebliche Aufwände', 'Aufwand', '-', TRUE),
  ('4800', '6800', 'Bürobedarf', 'Büro & IT', 'GuV: Sonstige betriebliche Aufwände', 'Aufwand', '-', TRUE),
  ('4810', '6810', 'Porto und Versand', 'Büro & IT', 'GuV: Sonstige betriebliche Aufwände', 'Aufwand', '-', TRUE),
  ('4820', '6820', 'Telefon und Internet', 'Büro & IT', 'GuV: Sonstige betriebliche Aufwände', 'Aufwand', '-', TRUE),
  ('4830', '6830', 'EDV-Kosten & Software-Lizenzen', 'Büro & IT', 'GuV: Sonstige betriebliche Aufwände', 'Aufwand', '-', TRUE),
  ('4840', '6840', 'Cloud & SaaS Abonnements', 'Büro & IT', 'GuV: Sonstige betriebliche Aufwände', 'Aufwand', '-', TRUE),
  ('4300', '6900', 'Versicherungen', 'Versicherungen', 'GuV: Sonstige betriebliche Aufwände', 'Aufwand', '-', TRUE),
  ('4310', '6910', 'Beiträge und Gebühren', 'Versicherungen', 'GuV: Sonstige betriebliche Aufwände', 'Aufwand', '-', TRUE),
  ('4820', '6200', 'AfA Sachanlagen', 'Abschreibungen', 'GuV: Abschreibungen', 'Aufwand', '-', TRUE),
  ('4821', '6201', 'AfA immaterielle Vermögen', 'Abschreibungen', 'GuV: Abschreibungen', 'Aufwand', '-', TRUE),
  ('4822', '6202', 'AfA Geringwertige Wirtschaftsgüter', 'Abschreibungen', 'GuV: Abschreibungen', 'Aufwand', '-', TRUE),
  ('4900', '6980', 'Sonstige Betriebskosten', 'Sonstige', 'GuV: Sonstige betriebliche Aufwände', 'Aufwand', '-', TRUE),
  ('4910', '6990', 'Sonstige Kosten allgemein', 'Sonstige', 'GuV: Sonstige betriebliche Aufwände', 'Aufwand', '-', TRUE),
  ('2100', '7100', 'Zinserträge', 'Finanzergebnis', 'GuV: Finanzergebnis', 'Ertrag', '+', TRUE),
  ('2120', '7120', 'Erträge Beteiligungen', 'Finanzergebnis', 'GuV: Finanzergebnis', 'Ertrag', '+', TRUE),
  ('2200', '7200', 'Zinsaufwand kurzfristig', 'Finanzergebnis', 'GuV: Finanzergebnis', 'Aufwand', '-', TRUE),
  ('2210', '7210', 'Zinsaufwand langfristig', 'Finanzergebnis', 'GuV: Finanzergebnis', 'Aufwand', '-', TRUE),
  ('2300', '7300', 'Kursverluste / Kursgewinne', 'Finanzergebnis', 'GuV: Finanzergebnis', 'Aufwand', '+-', TRUE),
  ('7600', '8600', 'Körperschaftsteuer', 'Steuern', 'GuV: Steuern', 'Aufwand', '-', TRUE),
  ('7620', '8620', 'Gewerbesteuer', 'Steuern', 'GuV: Steuern', 'Aufwand', '-', TRUE),
  ('7640', '8640', 'Umsatzsteuer-Zahllast', 'Steuern', 'GuV: Steuern', 'Aufwand', '-', TRUE),
  ('100', '100', 'Grundstücke & Gebäude', 'Anlagevermögen', 'Bilanz Aktiva: Anlagevermögen', 'Aktiva', '+', TRUE),
  ('200', '200', 'Maschinen & Anlagen', 'Anlagevermögen', 'Bilanz Aktiva: Anlagevermögen', 'Aktiva', '+', TRUE),
  ('400', '400', 'Fahrzeuge', 'Anlagevermögen', 'Bilanz Aktiva: Anlagevermögen', 'Aktiva', '+', TRUE),
  ('650', '650', 'BGA (Betriebs- & Geschäftsausst.)', 'Anlagevermögen', 'Bilanz Aktiva: Anlagevermögen', 'Aktiva', '+', TRUE),
  ('800', '800', 'Software / immaterielle WG', 'Anlagevermögen', 'Bilanz Aktiva: Anlagevermögen', 'Aktiva', '+', TRUE),
  ('1000', '1000', 'Kasse', 'Kassenbestand', 'Bilanz Aktiva: Umlaufvermögen', 'Aktiva', '+', TRUE),
  ('1200', '1800', 'Bank (Girokonten)', 'Bankguthaben', 'Bilanz Aktiva: Umlaufvermögen', 'Aktiva', '+', TRUE),
  ('1210', '1810', 'Bank 2 (z.B. Sparkasse)', 'Bankguthaben', 'Bilanz Aktiva: Umlaufvermögen', 'Aktiva', '+', TRUE),
  ('1400', '1200', 'Forderungen aus LuL', 'Forderungen', 'Bilanz Aktiva: Umlaufvermögen', 'Aktiva', '+', TRUE),
  ('1410', '1210', 'Forderungen verbundene Unternehmen', 'Forderungen', 'Bilanz Aktiva: Umlaufvermögen', 'Aktiva', '+', TRUE),
  ('1460', '1260', 'Geleistete Anzahlungen', 'Forderungen', 'Bilanz Aktiva: Umlaufvermögen', 'Aktiva', '+', TRUE),
  ('1500', '1400', 'Vorräte / Fertigerzeugnisse', 'Vorräte', 'Bilanz Aktiva: Umlaufvermögen', 'Aktiva', '+', TRUE),
  ('1570', '1570', 'Vorsteuer 19%', 'Vorsteuer', 'Bilanz Aktiva: Umlaufvermögen', 'Aktiva', '+', TRUE),
  ('1576', '1576', 'Vorsteuer 7%', 'Vorsteuer', 'Bilanz Aktiva: Umlaufvermögen', 'Aktiva', '+', TRUE),
  ('2000', '3000', 'Stammkapital / gezeichnetes Kapital', 'Eigenkapital', 'Bilanz Passiva: Eigenkapital', 'Passiva', '+', TRUE),
  ('2010', '3010', 'Rücklagen', 'Eigenkapital', 'Bilanz Passiva: Eigenkapital', 'Passiva', '+', TRUE),
  ('2020', '3020', 'Gewinn-/Verlustvortrag', 'Eigenkapital', 'Bilanz Passiva: Eigenkapital', 'Passiva', '+', TRUE),
  ('2030', '3030', 'Jahresüberschuss / -fehlbetrag', 'Eigenkapital', 'Bilanz Passiva: Eigenkapital', 'Passiva', '+', TRUE),
  ('2100', '3500', 'Darlehen (langfristig)', 'Fremdkapital', 'Bilanz Passiva: Verbindlichkeiten', 'Passiva', '+', TRUE),
  ('2110', '3510', 'Darlehen (kurzfristig < 1 Jahr)', 'Fremdkapital', 'Bilanz Passiva: Verbindlichkeiten', 'Passiva', '+', TRUE),
  ('1600', '3200', 'Verbindlichkeiten aus LuL', 'Fremdkapital', 'Bilanz Passiva: Verbindlichkeiten', 'Passiva', '+', TRUE),
  ('1700', '3730', 'USt-Zahllast (Umsatzsteuer)', 'Steuervb.', 'Bilanz Passiva: Verbindlichkeiten', 'Passiva', '+', TRUE),
  ('1740', '3740', 'Lohnsteuer-Verbindlichkeit', 'Steuervb.', 'Bilanz Passiva: Verbindlichkeiten', 'Passiva', '+', TRUE),
  ('1800', '3980', 'Sonstige Verbindlichkeiten', 'Fremdkapital', 'Bilanz Passiva: Verbindlichkeiten', 'Passiva', '+', TRUE),
  ('1900', '3900', 'Rückstellungen allgemein', 'Rückstellungen', 'Bilanz Passiva: Rückstellungen', 'Passiva', '+', TRUE),
  ('1910', '3910', 'Steuerrückstellungen', 'Rückstellungen', 'Bilanz Passiva: Rückstellungen', 'Passiva', '+', TRUE),
  ('1920', '3920', 'Sozialversicherungsrückstellungen', 'Rückstellungen', 'Bilanz Passiva: Rückstellungen', 'Passiva', '+', TRUE);
